@ECHO OFF
TITLE INIT_ENV
ECHO.
:: ###### GENERAL DEFINITIONS ######
::SET CURRENT_PATH=%cd%
SET FILENAME=MY_INFO.TXT
SET BANNER=res/banner
SET BASE64_PATH=res/TextToBase64/TextToBase64
:: ###### KEYSTORE DEFINITIONS ######
SET KEY_ALG=RSA
SET KEY_SIZE=2048
SET KEY_VALIDITY=365
SET KEYTOOL_FLAGS=-genkey -keystore keystore.jks -alias client -keyalg %KEY_ALG% -validity %KEY_VALIDITY% -keysize %KEY_SIZE%

FOR /F "tokens=* delims=" %%x in (%BANNER%) DO echo %%x

ECHO STARTING JOBS...
ECHO.
ECHO ===================
ECHO ^| *** WARNING *** ^|
ECHO ===================
ECHO.
ECHO OBTAINING JAVA_HOME VARIABLE FROM SYSTEM ENVIRONMENT VARIABLES . . .    
:: 
SET "JDK_PATH=%JAVA_HOME%"
SET JDK_PATH=%JAVA_HOME%\bin
:: PATH EXAMPLES:
::  
::
IF NOT DEFINED JDK_PATH (
ECHO.
ECHO PATH NOT FOUND!
ECHO FOR MORE INFORMATION SEE THE COMMENTS ON THIS FILE.
EXIT
) ELSE (
ECHO.
ECHO PATH FOUND!
ECHO %JDK_PATH%
ECHO.
ECHO.
)
SET KEYTOOL_PATH="%JDK_PATH%\keytool.exe"
SET /p KEYSTORE_ALIAS=Set an alias for your keystore: 
ECHO.
ECHO THE SECOND LINE IS THE ALIAS AND THIRD LINE IS THE PASSWORD > %FILENAME%
ECHO ALIAS: %KEYSTORE_ALIAS%
ECHO %KEYSTORE_ALIAS% >> %FILENAME%
ECHO.
CD /D java/LicenseDemo/res
@%KEYTOOL_PATH% %KEYTOOL_FLAGS%
CD /D ../../..
SET /p KEYSTORE_PASS=Type again the password: 
javac "%BASE64_PATH%.java"
java  "%BASE64_PATH%" %KEYSTORE_PASS% >> %FILENAME%
CLS
ECHO.
ECHO.
ECHO ALIAS AND PASSWORD SAVED IN %FILENAME%
ECHO.
ECHO.