/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ids_IDsCollector */

#ifndef _Included_ids_IDsCollector
#define _Included_ids_IDsCollector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ids_IDsCollector
 * Method:    getHDD_ID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ids_IDsCollector_getHDD_1ID
  (JNIEnv *, jobject);

/*
 * Class:     ids_IDsCollector
 * Method:    getBIOS_ID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ids_IDsCollector_getBIOS_1ID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
